###
GET http://localhost:5000/api/product

# create product
###
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "name": "test Product 4",
    "price": 500,
    "desc": "description",
    "productNumbers": [{
        "number": 101,
        "unavaibleDates": ["2024-01-21", "2024-01-24"]
    }]
    
}

#  # get haircut
#  ###
#  GET http://localhost:5000/api/haircut/690aedc8762c304d4673a25a

# update product
###
PUT http://localhost:5000/api/product/690adf27c9728f31e7c851a7
Content-Type: application/json

{
  "name": "updated product",
  "price": 10000
}

# delete product
###
DELETE http://localhost:5000/api/product/690adf27c9728f31e7c851a7

# get bookings
###
GET http://localhost:5000/api/bookings

# create bookings
###
POST http://localhost:5000/api/bookings
Content-Type: application/json

{
  "productId": "690adf32c9728f31e7c851a9",
  "name": "anjayani",
  "email": "sigma@gmail.com",
  "checkInDate": "2024-01-05",
  "checkOutDate": "2024-01-05"

}

# update Booking
###
PUT http://localhost:5000/api/bookings/690b5689bef71edb22383e1b
Content-Type: application/json

{
  "name": "update name",
  "email": "updateemail@gmail.com"
}

# delete Booking
###
DELETE  http://localhost:5000/api/bookings/690b5689bef71edb22383e1b

# get users
###
GET http://localhost:5000/api/users 

# create
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "bangka belitung",
  "email": "mabarbang@gmail.com",
  "password": "anjaymabar2"

}

# login
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "mabarbang@gmail.com",
  "password": "anjaymabar2"
}

#logout User
###
http://localhost:5000/api/users/logout

# check auth
###
GET http://localhost:5000/auth
